const $=s=>document.querySelector(s);const v=$("#video"),o=$("#overlay"),oc=o.getContext("2d"),w=$("#work"),wc=w.getContext("2d",{willReadFrequently:true});let stream=null,active=false,cal=false,running=false,raf=0,prev=null,last=0,shots=[],cfg={s:72,a:4,m:180,c:450},fn=0,ft=performance.now();
function state(t,c){$("#state").textContent=t;$("#state").className=c}function resize(){if(!v.videoWidth)return;o.width=v.videoWidth;o.height=v.videoHeight;w.width=480;w.height=Math.round(480*v.videoHeight/v.videoWidth);draw()}
function draw(p){oc.clearRect(0,0,o.width,o.height);if(cal){oc.strokeStyle="#22c55e";oc.lineWidth=4;oc.strokeRect(o.width*.04,o.height*.04,o.width*.92,o.height*.92)}if(p){let r=Math.max(12,o.width/70);oc.beginPath();oc.arc(p.x,p.y,r,0,Math.PI*2);oc.strokeStyle="#fff";oc.lineWidth=3;oc.stroke();oc.beginPath();oc.arc(p.x,p.y,r*.65,0,Math.PI*2);oc.fillStyle="#ef4444";oc.fill()}}
async function start(){try{if(!navigator.mediaDevices?.getUserMedia)throw Error("La cámara requiere HTTPS.");if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:"environment"},width:{ideal:1280},height:{ideal:1920}}});v.srcObject=stream;await new Promise(r=>v.onloadedmetadata=r);await v.play();active=true;resize();state("CÁMARA ON","on");$("#startBox").style.display="none";$("#cal").disabled=false;$("#info").textContent="Cámara activa. Calibrá el blanco.";raf=requestAnimationFrame(loop)}catch(e){state("ERROR CÁMARA","err");$("#startBox").querySelector("h2").textContent="No se pudo abrir la cámara";$("#startBox").querySelector("p").textContent=e.message}}
function calibrate(){cal=true;draw();$("#go").disabled=false;$("#info").textContent="Calibrado. Iniciá la sesión."}function go(){running=true;shots=[];prev=null;last=0;render();$("#go").disabled=true;$("#stop").disabled=false;$("#info").textContent="SESIÓN ACTIVA: detectando destellos rojos."}function stop(){running=false;$("#go").disabled=false;$("#stop").disabled=true;$("#info").textContent="Sesión detenida."}
function detect(){wc.drawImage(v,0,0,w.width,w.height);let d=wc.getImageData(0,0,w.width,w.height).data,sx=0,sy=0,n=0,s=cfg.s/100;for(let y=0;y<w.height;y+=2)for(let x=0;x<w.width;x+=2){let i=(y*w.width+x)*4,r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx?((mx-mn)/mx):0;if(r>160+s*30&&sat>.52&&r-Math.max(g,b)>82+s*18){sx+=x;sy+=y;n++}}if(n<cfg.a||n>cfg.m)return null;return{x:sx/n*(v.videoWidth/w.width),y:sy/n*(v.videoHeight/w.height)}}
function flash(p){if(!prev){prev=p;return true}let d=Math.hypot(p.x-prev.x,p.y-prev.y);prev=p;return d<Math.max(80,v.videoWidth*.08)}
function add(p){let t=performance.now();if(t-last<cfg.c)return;let inter=shots.length?(t-shots.at(-1).ts)/1000:null;last=t;shots.push({n:shots.length+1,ts:t,t:new Date().toLocaleTimeString(),x:p.x,y:p.y,inter});$("#flash").classList.add("show");setTimeout(()=>$("#flash").classList.remove("show"),180);render()}
function render(){let ints=shots.filter(x=>x.inter).map(x=>x.inter);$("#n").textContent=shots.length;$("#last").textContent=shots.length&&shots.at(-1).inter?shots.at(-1).inter.toFixed(2)+"s":"—";$("#avg").textContent=ints.length?(ints.reduce((a,b)=>a+b,0)/ints.length).toFixed(2)+"s":"—";$("#list").innerHTML=shots.length?shots.slice().reverse().map(x=>`<div class="item"><div class="badge">🔴</div><div><b>Disparo #${x.n}</b><br><small>${x.t} · X ${Math.round(x.x)} · Y ${Math.round(x.y)}</small></div><strong>DETECTADO</strong></div>`).join(""):"Sin disparos."}
function loop(){if(!active)return;fn++;let t=performance.now();if(t-ft>1000){$("#fps").textContent=fn;fn=0;ft=t}let p=detect();if(p){$("#laser").textContent="● DESTELLO ROJO";$("#laser").classList.add("hit");draw(p);if(running&&flash(p))add(p)}else{$("#laser").textContent="● ESPERANDO LÁSER";$("#laser").classList.remove("hit");draw()}raf=requestAnimationFrame(loop)}
$("#start").onclick=start;$("#cal").onclick=calibrate;$("#go").onclick=go;$("#stop").onclick=stop;$("#reload").onclick=()=>location.reload();$("#clear").onclick=()=>{shots=[];prev=null;render()};$("#sens").oninput=e=>{cfg.s=+e.target.value;$("#sv").textContent=cfg.s+"%"};$("#area").oninput=e=>{cfg.a=+e.target.value;$("#av").textContent=cfg.a};$("#maxarea").oninput=e=>{cfg.m=+e.target.value;$("#xv").textContent=cfg.m};$("#cool").oninput=e=>{cfg.c=+e.target.value;$("#cv").textContent=cfg.c+" ms"};v.addEventListener("loadedmetadata",resize);window.addEventListener("resize",resize);