const $=s=>document.querySelector(s);const video=$("#video"),overlay=$("#overlay"),ctx=overlay.getContext("2d"),work=document.createElement("canvas"),wctx=work.getContext("2d",{willReadFrequently:true});let stream=null,active=false,calibrated=false,last=0,session=0,shots=[],cooldown=500;const cfg={red:150,ratio:1.55,min:2};
function setErr(t){$("#error").textContent=t;$("#error").classList.remove("hidden")}
function resize(){if(!video.videoWidth)return;overlay.width=video.videoWidth;overlay.height=video.videoHeight;work.width=Math.min(640,video.videoWidth);work.height=Math.round(work.width*video.videoHeight/video.videoWidth);draw()}
function draw(){ctx.clearRect(0,0,overlay.width,overlay.height);if(!overlay.width)return;ctx.strokeStyle=calibrated?'#22c55e':'#f59e0b';ctx.lineWidth=Math.max(3,overlay.width/300);ctx.strokeRect(overlay.width*.05,overlay.height*.05,overlay.width*.9,overlay.height*.9)}
async function camera(){try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Este navegador/origen no permite cámara. Usá Safari con HTTPS.');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();resize();$("#cameraBtn").disabled=true;$("#calBtn").disabled=false;$("#message").textContent='Cámara activa. Encadrá el blanco completo.';$("#status").textContent='● Cámara activa';loop()}catch(e){setErr('Cámara: '+e.message+' — Si abriste el HTML desde un archivo, no funcionará en iPhone. Debe publicarse en HTTPS.')}}
function calibrate(){calibrated=true;draw();$("#sessionBtn").disabled=false;$("#message").textContent='Blanco calibrado. Iniciá la sesión.'}
function start(){if(!calibrated)return;active=true;session=Date.now();last=0;$("#sessionBtn").disabled=true;$("#stopBtn").disabled=false;$("#message").textContent='Sesión activa. Probá el láser rojo.'}
function stop(){active=false;$("#sessionBtn").disabled=false;$("#stopBtn").disabled=true;$("#message").textContent='Sesión detenida.'}
function detect(){if(!video.videoWidth)return;wctx.drawImage(video,0,0,work.width,work.height);const d=wctx.getImageData(0,0,work.width,work.height).data;let sx=0,sy=0,n=0,maxR=0;for(let y=2;y<work.height-2;y+=2){for(let x=2;x<work.width-2;x+=2){const i=(y*work.width+x)*4,r=d[i],g=d[i+1],b=d[i+2];if(r>maxR)maxR=r;if(r>cfg.red&&r>g*cfg.ratio&&r>b*cfg.ratio){sx+=x;sy+=y;n++}}}$("#debug").textContent=`rojo detectado: ${n}px · R máx: ${maxR}`;if(n<cfg.min)return null;return{x:sx/n*overlay.width/work.width,y:sy/n*overlay.height/work.height,n}}
function score(x,y){const cx=overlay.width*.535,cy=overlay.height*.56,rx=overlay.width*.19,ry=overlay.height*.31;const d=Math.hypot((x-cx)/rx,(y-cy)/ry);return d<=.22?5:d<=.55?4:d<=.82?3:d<=1?2:0}
function hit(p){const now=Date.now();if(now-last<cooldown)return;last=now;const s=score(p.x,p.y);shots.push({n:shots.length+1,s,time:new Date(now).toLocaleTimeString(),x:Math.round(p.x),y:Math.round(p.y)});ctx.beginPath();ctx.arc(p.x,p.y,11,0,Math.PI*2);ctx.fillStyle='#ef4444';ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 15px sans-serif';ctx.fillText(String(s),p.x+15,p.y+5);render()}
function render(){const total=shots.reduce((a,b)=>a+b.s,0);$("#shots").textContent=shots.length;$("#score").textContent=total;$("#avg").textContent=(shots.length?total/shots.length:0).toFixed(1);$("#list").innerHTML=shots.length?shots.slice().reverse().map(x=>`<div class="hit"><div class="badge">${x.s}</div><div><b>Disparo #${x.n}</b><br><small>${x.time} · X ${x.x} · Y ${x.y}</small></div><b>${x.s} pts</b></div>`).join(''):'Sin impactos.'}
function loop(){if(video.readyState>=2){draw();if(active){const p=detect();if(p)hit(p)}}requestAnimationFrame(loop)}
$("#cameraBtn").onclick=camera;$("#calBtn").onclick=calibrate;$("#sessionBtn").onclick=start;$("#stopBtn").onclick=stop;$("#clearBtn").onclick=()=>{shots=[];render();draw()};video.onloadedmetadata=resize;window.onresize=resize;